apps/friends/urls.py
from django.conf.urls import url
from . import views


app_name = "friends"

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^remove/(?P<id>\d+)$', views.remove, name="remove"),
	url(r'^add/(?P<id>\d+)$', views.add, name="add"),
	url(r'^view/(?P<id>\d+)$', views.view, name="view"),
]

apps/manager/urls.py
from django.conf.urls import url
from . import views


app_name = "manager"

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^register$', views.register, name="register"),
	url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout"),
]

beltexam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^friends/', include('apps.friends.urls', namespace="friends")),
    url(r'^', include('apps.manager.urls', namespace="manager")),

]

apps/friends/models.py
from __future__ import unicode_literals
from django.db import models

apps/manager/models.py
from __future__ import unicode_literals
from django.db import models

import re
import bcrypt

class UserManager(models.Manager):

	def create_user(self, name, alias, email, dob, pw_hash):
		user = self.create(name=name, alias=alias, email=email, dob=dob, pw_hash=pw_hash)
		return user

	def hash_password(self, password):
		password = password.encode()
		hashed_pw = bcrypt.hashpw(password, bcrypt.gensalt())
		return hashed_pw

	def login_check(self, data):
		errors=[]
		email = data['email']
		password = data['password'].encode()
		try:
			user = self.get(email=email)
			hashed_pw = user.pw_hash.encode()
			if bcrypt.hashpw(password, hashed_pw) == hashed_pw:
				return (True, user)
		except:
			errors.append("Incorrect email or password")

		return (False, errors)

	def validate_registration(self, data):
		errors = []
		name = data['name']
		alias = data['alias']
		email = data['email']
		dob = data['dob']
		password = data['password']

		if len(name) < 2:
			errors.append("Please enter your name.")
		if len(alias) < 2:
			errors.append("Please enter an alias")
		if len(email) < 1:
			errors.append("Please enter an email address.")
		elif not re.match( r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", email):
			errors.append("Please enter a valid email address")
		if len(password) < 8:
			errors.append("Password must have atleast 8 characters")

		if not errors:
			try:
				matches = self.get(email=email)
				errors.append("A user already exists with that email.")
				return (False, errors)
			except:
				pw_hash = self.hash_password(data['password'])
				user = self.create_user(data['name'], data['alias'], data['email'], data['dob'], pw_hash)
				return (True, user)
		else:
			return (False, errors)


class User(models.Model):
	name = models.CharField(max_length=255)
	alias = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	dob = models.DateTimeField(auto_now_add=False)
	friend = models.ManyToManyField("self", related_name="my_friend", null=True)
	pw_hash = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

apps/friends/views.py
from django.shortcuts import render, redirect
from ..manager.models import User

def index(request):

	user = request.session['user_id']
	context = {
		'users' : User.objects.all(),
		'friends': User.objects.filter(friend=user)

	}

	return render(request, 'friends/index.html', context)

def add(request, id):



	user_id = request.session['user_id']

	new_friend = User.objects.get(id=id)
	user = User.objects.get(id=user_id)
	new_friend.friend.add(user)
	new_friend.save()


	return redirect('friends:index')

def remove(request, id):


    user_id = request.session['user_id']

    my_friend = User.objects.get(id=id)
    user = User.objects.get(id=user_id)
    my_friend.friend.remove(user)
    my_friend.save()


    return redirect('friends:index')

def view(request, id):

    context= {
        'friends': User.objects.filter(id=id)
    }
    friend = User.objects.get(id=id)

    return render(request, 'friends/friendprofile.html', context)

apps/manager/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User



# Create your views here.
def index(request):
	return render(request, 'manager/index.html')

def register(request):
	if request.method == "POST":
		valid, response = User.objects.validate_registration(request.POST)
		if valid:
			messages.success(request, "Congrats, {}! You've successfully registered! Now Log In!".format(response.name))
			request.session['user_id'] = response.id
			return redirect('manager:index')
		else:
			for error in response:
				messages.error(request, error)

	return redirect('manager:index')

def login(request):
	if request.method == "POST":

		valid, response = User.objects.login_check(request.POST)
		if valid:
			request.session['user_id'] = response.id
			request.session['alias'] = response.alias
			request.session['name'] = response.name

			return redirect('friends:index')


		else:
			for error in response:
				messages.error(request, error)

	return redirect('manager:index')




def view(request,id):

	if request.method == "GET":
		friend = User.objects.get(id=id)
        context= {
            'friends': User.objects.filter(id=id)
        }

	return render(request, 'manager/friendprofile.html', context)

def logout(request):
    if request.method == "POST":
        if 'user_id' in request.session:
            del request.session['user_id']
            print "user has logged out!"
    return redirect('manager:index')

apps/friends/templates/friends/friendprofile.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Friend Profile</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'friends/css/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>

    <body>
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="myNavbar">
                <!-- <ul class="nav navbar-nav">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                </ul> -->
                <ul class="nav navbar-nav navbar-right">

                    <li>
                        <form class="navbar-form form-inline pull-right" action="{% url 'manager:logout' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Logout</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-12">

                    {% for friend in friends %}
                    <h5>Alias:</h5> <p>{{friend.alias}}</p>
                    <h5>Email:</h5> <p>{{friend.email}}</p>
                    <h5>Birthday:</h5> <p>{{friend.dob}}</p>


                    {% endfor %}
                    <form class="form-horizontal" action="{% url 'friends:index'   %}" method="get">
                        {% csrf_token %}
                        <div class="form-group ">
                            <button type="submit"class="btn-lg btn-block login-button">Return Home</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>



        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'course_app/js/script.js' %}"></script>
    </body>
</html>

apps/friends/templates/friends/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Friend App | Home</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'friends/css/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #707070;
        text-align: left;
        padding: 8px;
    }

    td {
        border-right: 1px solid #707070;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    button {
        color: white;
    }
    </style>

    </head>
    <body>
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="myNavbar">
                <!-- <ul class="nav navbar-nav">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                </ul> -->
                <ul class="nav navbar-nav navbar-right">

                    <li>
                        <form class="navbar-form form-inline pull-right" action="{% url 'manager:logout' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Logout</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>


		<center><h4>Welcome, {{ request.session.name }}.</h4>
        <p>Here is a list of your friends</p></center>

            <div class="container">
                <div class="container">

                    <!-- users who are friends already -->
                    <div class="row">
                        <div class="col-6 col-lg-6">
                            <center><h4 class="title">These aren't your friends yet</h4></center>
                            <table>
                                <tr>
                                    <th><h4>Alias</h4></th>
                                    <th><h4>Action</h4></th>
                                </tr>
                                <tr>
                                {% for user in users %}

                                    <td>{{user.alias}}</td>

                                    <td>

                                        <form action="{% url 'friends:add' user.id %}" method="post">
                                            {% csrf_token %}
                                            <div class="form-group ">
                                                <button type="submit" class="btn-sm btn-block login-button">Add Friend</button>
                                            </div>
                                        </form>
                                        <div class="form-group ">
                                            <a href="{% url 'friends:view' user.id %}"><button class="btn-sm btn-block login-button">View Profile</button></a>
                                        </div>


                                    </td>
                                </tr>

                                {% endfor %}
                            </table>

                        </div>

                        <!-- users who aren't friends yet -->
                        <div class="col-6 col-lg-6">
                            <center><h4 class="title">These are your current friends</h4></center>
                            <table>
                                <tr>
                                    <th><h4>Alias</h4></th>
                                    <th><h4>Action</h4></th>
                                </tr>
                                <tr>
                                {% for friend in friends %}
                                    <td>{{friend.alias}}</td>
                                    <td>
                                        <form action="{% url 'friends:remove' friend.id %}" method="post">
                                            {% csrf_token %}
                                            <div class="form-group ">
                                                <button type="submit" class="btn-sm btn-block login-button">Remove</button>
                                            </div>
                                        </form>
                                        <div class="form-group ">
                                            <a href="{% url 'friends:view' friend.id %}"><button class="btn-sm btn-block login-button">View Profile</button></a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>

                        </div>
                    </div>
                </div>
            </div>



        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'course_app/js/script.js' %}"></script>
    </body>
</html>

apps/manager/templates/manager/index.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Login and Registration</title>
        {% load static %}
        <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'manager/css/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- <link rel="stylesheet" href="{% static 'course_app/css/style.css' %}"> -->

    </head>
<body>
	{% for message in messages %}
		<center>{{ message }}</center>
	{% endfor %}


    <body>
        <div class="container-fluid">
            <center><h3>LOGIN</h3></center>
            <center><form class="form-horizontal" method="post" action="{% url 'manager:login' %}">
                {% csrf_token %}
                <input type="text" name="email" placeholder="Email">
                <input type="password" name="password" placeholder="Password">
                <button type="submit" class="btn btn-primary">Log In </button>
            </form>
            {% for error in errors %}
                {{errors}}
            {% endfor %}</center>

        </div>
        <div class="container-fluid">
            <center><h3>REGISTER</h3></center>
            <form class="form-horizontal" method="post" action="{% url 'manager:register' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name" class="cols-sm-2 control-label">Your Name</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                            <input type="text" class="form-control" name="name" id="name"  placeholder="Enter your Name"/>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="name" class="cols-sm-2 control-label">Your Alias</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                            <input type="text" class="form-control" name="alias" id="alias"  placeholder="Enter your Alias"/>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="cols-sm-2 control-label">Your Email</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                            <input type="text" class="form-control" name="email" id="email"  placeholder="Enter your Email"/>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="cols-sm-2 control-label">Password</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                            <input type="password" class="form-control" name="password" id="password"  placeholder="Password must be atleast 8 characters"/>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="cols-sm-2 control-label">Confirm Password</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                            <input type="password" class="form-control" name="confirm" id="confirm"  placeholder="Confirm Your Password"/>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="dob" class="cols-sm-2 control-label">Enter Your DOB</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                            <input id="dob" name="dob" type="date" value="1991-01-13"/>
                        </div>
                    </div>
                </div>
                <div class="form-group ">
                    <button type="submit" class="btn btn-primary btn-lg btn-block login-button">Register</button>
                </div>
            </form>
            {% for error in errors %}
                {{errors}}
            {% endfor %}
        </div>





        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>

</body>
</html>